version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "879772956301"
    AWS_DEFAULT_REGION: "ap-southeast-1"
    IMAGE_REPO_NAME: "order"
    CODEBUILD_RESOLVED_SOURCE_VERSION: "latest"

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $IMAGE_REPO_NAME
      - echo $AWS_ACCOUNT_IDecho $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - 
      - echo $AWS_DEFAULT_REGION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo start command
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd order
      - mvn package -Dmaven.test.skip=true
      - echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      - echo $pwd
      - echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION  .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo $pwd
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION

cache:
  paths:
    - '/root/.m2/**/*'
