
---

apiVersion: v1
kind: Service
metadata:
  name: productdelivery
  labels:
    app: productdelivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: productdelivery


---


apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order


---


apiVersion: v1
kind: Service
metadata:
  name: marketing
  labels:
    app: marketing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: marketing


---


apiVersion: v1
kind: Service
metadata:
  name: orderstatus
  labels:
    app: orderstatus
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: orderstatus
    
    
---


apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: payment